kind = "DojoModel"
class_hash = "0x263bba5fd559f8a5928728b0f7ed835e3832d9e64f39676cbf3fa6d675299c7"
original_class_hash = "0x263bba5fd559f8a5928728b0f7ed835e3832d9e64f39676cbf3fa6d675299c7"
abi = "manifests/dev/abis/base/models/dojo_starter_models_blobert_blobert_2_blobert_two.json"
name = "dojo_starter::models::blobert::blobert_2::blobert_two"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "blobert_id"
type = "u8"
key = true

[[members]]
name = "health"
type = "u8"
key = false
