kind = "DojoModel"
class_hash = "0x245e535b8f5b9ae24c8251180feaa7e54ba2ce79a26fe99b35319a96a98d7b"
original_class_hash = "0x245e535b8f5b9ae24c8251180feaa7e54ba2ce79a26fe99b35319a96a98d7b"
abi = "manifests/dev/abis/base/models/dojo_starter_models_blobert_blobert_2_blobert_two.json"
name = "dojo_starter::models::blobert::blobert_2::blobert_two"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "blobert_id"
type = "u128"
key = true

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "blobet_side_effect"
type = "SideEffectType"
key = false
