kind = "DojoModel"
class_hash = "0x10db05db0f31e825a1276173b5cb9933fe1d7586831f7211807dcd6551883c3"
original_class_hash = "0x10db05db0f31e825a1276173b5cb9933fe1d7586831f7211807dcd6551883c3"
abi = "manifests/dev/abis/base/models/dojo_starter_models_blobert_blobert_5_blobert_five.json"
name = "dojo_starter::models::blobert::blobert_5::blobert_five"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "blobert_id"
type = "u128"
key = true

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "blobet_side_effect"
type = "SideEffectType"
key = false
