kind = "DojoModel"
class_hash = "0x569c81884a1692aa5c4411812b27dddaf45ef27fe1aa9fe5c05ec58312d095c"
original_class_hash = "0x569c81884a1692aa5c4411812b27dddaf45ef27fe1aa9fe5c05ec58312d095c"
abi = "manifests/dev/abis/base/models/dojo_starter_models_blobert_lineup_blobert_lineup.json"
name = "dojo_starter::models::blobert_lineup::blobert_lineup"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "blobert_1"
type = "u128"
key = false

[[members]]
name = "blobert_2"
type = "u128"
key = false

[[members]]
name = "blobert_3"
type = "u128"
key = false

[[members]]
name = "blobert_4"
type = "u128"
key = false

[[members]]
name = "blobert_5"
type = "u128"
key = false

[[members]]
name = "blobert_6"
type = "u128"
key = false
