kind = "DojoModel"
class_hash = "0x3a7305310c7b2884ffc76c0337e9ca7062774d83895db48f5f698afedd74ea7"
original_class_hash = "0x3a7305310c7b2884ffc76c0337e9ca7062774d83895db48f5f698afedd74ea7"
abi = "manifests/dev/abis/base/models/dojo_starter_models_blobert_blobert_1_blobert_one.json"
name = "dojo_starter::models::blobert::blobert_1::blobert_one"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "blobert_id"
type = "u8"
key = true

[[members]]
name = "health"
type = "u8"
key = false
