kind = "DojoModel"
class_hash = "0x2b34ac398807c689fb7f43e04c2c38b715d406800fcdf47090c032f7fd5e5f0"
original_class_hash = "0x2b34ac398807c689fb7f43e04c2c38b715d406800fcdf47090c032f7fd5e5f0"
abi = "manifests/dev/abis/base/models/dojo_starter_models_blobert_blobert_6_blobert_six.json"
name = "dojo_starter::models::blobert::blobert_6::blobert_six"

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "blobert_id"
type = "u128"
key = true

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "blobet_side_effect"
type = "SideEffectType"
key = false
