export const customBlobertArray = [
  "_1337bert",
  "ambert",
  "blobert",
  "blobhetti",
  "bobbyrealms",
  "breadbert",
  "bulbert",
  "butterbert",
  "calbert",
  "casbert",
  "chelbert",
  "credbert",
  "delbert",
  "devbert",
  "dombert",
  "duckbert",
  "erbert",
  "fombert",
  "francaisbert",
  "GOATbert",
  "gobert",
  "goldbert",
  "grugbert",
  "guthbert",
  "hambert",
  "lanbert",
  "lootbert",
  "milbert",
  "mirbert",
  "moodbert",
  "nejbert",
  "neobert",
  "odbert",
  "pleurbert",
  "pobert",
  "raubert",
  "rebert",
  "redbert",
  "sebert",
  "shelbert",
  "squibert",
  "STARKbert",
  "sylbert",
  "tarbert",
  "tbert",
  "tenbert",
  "udbert",
  "wenbert",
];

export const customBlobertInfoObject = {
  _1337bert: { path: "/custom/_1337bert.png" },
  ambert: { path: "/custom/ambert.png" },
  blobert: { path: "/custom/blobert.png" },
  blobhetti: { path: "/custom/blobhetti.png" },
  bobbyrealms: { path: "/custom/bobbyrealms.png" },
  breadbert: { path: "/custom/breadbert.png" },
  bulbert: { path: "/custom/bulbert.png" },
  butterbert: { path: "/custom/butterbert.png" },
  calbert: { path: "/custom/calbert.png" },
  casbert: { path: "/custom/casbert.png" },
  chelbert: { path: "/custom/chelbert.png" },
  credbert: { path: "/custom/credbert.png" },
  delbert: { path: "/custom/delbert.png" },
  devbert: { path: "/custom/devbert.png" },
  dombert: { path: "/custom/dombert.png" },
  duckbert: { path: "/custom/duckbert.png" },
  erbert: { path: "/custom/erbert.png" },
  fombert: { path: "/custom/fombert.png" },
  francaisbert: { path: "/custom/francaisbert.png" },
  GOATbert: { path: "/custom/GOATbert.png" },
  gobert: { path: "/custom/gobert.png" },
  goldbert: { path: "/custom/goldbert.png" },
  grugbert: { path: "/custom/grugbert.png" },
  guthbert: { path: "/custom/guthbert.png" },
  hambert: { path: "/custom/hambert.png" },
  lanbert: { path: "/custom/lanbert.png" },
  lootbert: { path: "/custom/lootbert.png" },
  milbert: { path: "/custom/milbert.png" },
  mirbert: { path: "/custom/mirbert.png" },
  moodbert: { path: "/custom/moodbert.png" },
  nejbert: { path: "/custom/nejbert.png" },
  neobert: { path: "/custom/neobert.png" },
  odbert: { path: "/custom/odbert.png" },
  pleurbert: { path: "/custom/pleurbert.png" },
  pobert: { path: "/custom/pobert.png" },
  raubert: { path: "/custom/raubert.png" },
  rebert: { path: "/custom/rebert.png" },
  redbert: { path: "/custom/redbert.png" },
  sebert: { path: "/custom/sebert.png" },
  shelbert: { path: "/custom/shelbert.png" },
  squibert: { path: "/custom/squibert.png" },
  STARKbert: { path: "/custom/STARKbert.png" },
  sylbert: { path: "/custom/sylbert.png" },
  tarbert: { path: "/custom/tarbert.png" },
  tbert: { path: "/custom/tbert.png" },
  tenbert: { path: "/custom/tenbert.png" },
  udbert: { path: "/custom/udbert.png" },
  wenbert: { path: "/custom/wenbert.png" },
};

export const publicBlobertsPath = [
  "/custom/_1337bert.png",
  "/custom/ambert.png",
  "/custom/blobert.png",
  "/custom/blobhetti.png",
  "/custom/bobbyrealms.png",
  "/custom/breadbert.png",
  "/custom/bulbert.png",
  "/custom/butterbert.png",
  "/custom/calbert.png",
  "/custom/casbert.png",
  "/custom/chelbert.png",
  "/custom/credbert.png",
  "/custom/delbert.png",
  "/custom/devbert.png",
  "/custom/dombert.png",
  "/custom/duckbert.png",
  "/custom/erbert.png",
  "/custom/fombert.png",
  "/custom/francaisbert.png",
  "/custom/GOATbert.png",
  "/custom/gobert.png",
  "/custom/goldbert.png",
  "/custom/grugbert.png",
  "/custom/guthbert.png",
  "/custom/hambert.png",
  "/custom/lanbert.png",
  "/custom/lootbert.png",
  "/custom/milbert.png",
  "/custom/mirbert.png",
  "/custom/moodbert.png",
  "/custom/nejbert.png",
  "/custom/neobert.png",
  "/custom/odbert.png",
  "/custom/pleurbert.png",
  "/custom/pobert.png",
  "/custom/raubert.png",
  "/custom/rebert.png",
  "/custom/redbert.png",
  "/custom/sebert.png",
  "/custom/shelbert.png",
  "/custom/squibert.png",
  "/custom/STARKbert.png",
  "/custom/sylbert.png",
  "/custom/tarbert.png",
  "/custom/tbert.png",
  "/custom/tenbert.png",
  "/custom/udbert.png",
  "/custom/wenbert.png",
];
