export const customBlobertArray = [
    "_1337bert",
    "ambert",
    "blobert",
    "blobhetti",
    "bobbyrealms",
    "breadbert",
    "bulbert",
    "butterbert",
    "calbert",
    "casbert",
    "chelbert",
    "credbert",
    "delbert",
    "devbert",
    "dombert",
    "duckbert",
    "erbert",
    "fombert",
    "francaisbert",
    "GOATbert",
    "gobert",
    "goldbert",
    "grugbert",
    "guthbert",
    "hambert",
    "lanbert",
    "lootbert",
    "milbert",
    "mirbert",
    "moodbert",
    "nejbert",
    "neobert",
    "odbert",
    "pleurbert",
    "pobert",
    "raubert",
    "rebert",
    "redbert",
    "sebert",
    "shelbert",
    "squibert",
    "STARKbert",
    "sylbert",
    "tarbert",
    "tbert",
    "tenbert",
    "udbert",
    "wenbert"
]

export const customBlobertInfoObject = {
    "_1337bert": { path: "/assets/custom/_1337bert.png"},
    "ambert": {path: "/assets/custom/ambert.png"},
    "blobert": {path: "/assets/custom/blobert.png"},
    "blobhetti": {path: "/assets/custom/blobhetti.png"},
    "bobbyrealms": {path: "/assets/custom/bobbyrealms.png"},
    "breadbert": {path: "/assets/custom/breadbert.png"},
    "bulbert": {path: "/assets/custom/bulbert.png"},
    "butterbert": {path: "/assets/custom/butterbert.png"},
    "calbert": {path: "/assets/custom/calbert.png"},
    "casbert": {path: "/assets/custom/casbert.png"},
    "chelbert": {path: "/assets/custom/chelbert.png"},
    "credbert": {path: "/assets/custom/credbert.png"},
    "delbert": {path: "/assets/custom/delbert.png"},
    "devbert": {path: "/assets/custom/devbert.png"},
    "dombert": {path: "/assets/custom/dombert.png"},
    "duckbert": {path: "/assets/custom/duckbert.png"},
    "erbert": {path: "/assets/custom/erbert.png"},
    "fombert": {path: "/assets/custom/fombert.png"},
    "francaisbert": {path: "/assets/custom/francaisbert.png"},
    "GOATbert": {path: "/assets/custom/GOATbert.png"},
    "gobert": {path: "/assets/custom/gobert.png"},
    "goldbert": {path: "/assets/custom/goldbert.png"},
    "grugbert": {path: "/assets/custom/grugbert.png"},
    "guthbert": {path: "/assets/custom/guthbert.png"},
    "hambert": {path: "/assets/custom/hambert.png"},
    "lanbert": {path: "/assets/custom/lanbert.png"},
    "lootbert": {path: "/assets/custom/lootbert.png"},
    "milbert": {path: "/assets/custom/milbert.png"},
    "mirbert": {path: "/assets/custom/mirbert.png"},
    "moodbert": {path: "/assets/custom/moodbert.png"},
    "nejbert": {path: "/assets/custom/nejbert.png"},
    "neobert": {path: "/assets/custom/neobert.png"},
    "odbert": {path: "/assets/custom/odbert.png"},
    "pleurbert": {path: "/assets/custom/pleurbert.png"},
    "pobert": {path: "/assets/custom/pobert.png"},
    "raubert": {path: "/assets/custom/raubert.png"},
    "rebert": {path: "/assets/custom/rebert.png"},
    "redbert": {path: "/assets/custom/redbert.png"},
    "sebert": {path: "/assets/custom/sebert.png"},
    "shelbert": {path: "/assets/custom/shelbert.png"},
    "squibert": {path: "/assets/custom/squibert.png"},
    "STARKbert": {path: "/assets/custom/STARKbert.png"},
    "sylbert": {path: "/assets/custom/sylbert.png"},
    "tarbert": {path: "/assets/custom/tarbert.png"},
    "tbert": {path: "/assets/custom/tbert.png"},
    "tenbert": {path: "/assets/custom/tenbert.png"},
    "udbert": {path: "/assets/custom/udbert.png"},
    "wenbert": {path: "/assets/custom/wenbert.png"}
}