export const customBlobertArray = [
    "_1337bert",
    "ambert",
    "blobert",
    "blobhetti",
    "bobbyrealms",
    "breadbert",
    "bulbert",
    "butterbert",
    "calbert",
    "casbert",
    "chelbert",
    "credbert",
    "delbert",
    "devbert",
    "dombert",
    "duckbert",
    "erbert",
    "fombert",
    "francaisbert",
    "GOATbert",
    "gobert",
    "goldbert",
    "grugbert",
    "guthbert",
    "hambert",
    "lanbert",
    "lootbert",
    "milbert",
    "mirbert",
    "moodbert",
    "nejbert",
    "neobert",
    "odbert",
    "pleurbert",
    "pobert",
    "raubert",
    "rebert",
    "redbert",
    "sebert",
    "shelbert",
    "squibert",
    "STARKbert",
    "sylbert",
    "tarbert",
    "tbert",
    "tenbert",
    "udbert",
    "wenbert"
]

export const customBlobertInfoObject = {
    "_1337bert": { path: "/custom/_1337bert.png"},
    "ambert": {path: "/custom/ambert.png"},
    "blobert": {path: "/custom/blobert.png"},
    "blobhetti": {path: "/custom/blobhetti.png"},
    "bobbyrealms": {path: "/custom/bobbyrealms.png"},
    "breadbert": {path: "/custom/breadbert.png"},
    "bulbert": {path: "/custom/bulbert.png"},
    "butterbert": {path: "/custom/butterbert.png"},
    "calbert": {path: "/custom/calbert.png"},
    "casbert": {path: "/custom/casbert.png"},
    "chelbert": {path: "/custom/chelbert.png"},
    "credbert": {path: "/custom/credbert.png"},
    "delbert": {path: "/custom/delbert.png"},
    "devbert": {path: "/custom/devbert.png"},
    "dombert": {path: "/custom/dombert.png"},
    "duckbert": {path: "/custom/duckbert.png"},
    "erbert": {path: "/custom/erbert.png"},
    "fombert": {path: "/custom/fombert.png"},
    "francaisbert": {path: "/custom/francaisbert.png"},
    "GOATbert": {path: "/custom/GOATbert.png"},
    "gobert": {path: "/custom/gobert.png"},
    "goldbert": {path: "/custom/goldbert.png"},
    "grugbert": {path: "/custom/grugbert.png"},
    "guthbert": {path: "/custom/guthbert.png"},
    "hambert": {path: "/custom/hambert.png"},
    "lanbert": {path: "/custom/lanbert.png"},
    "lootbert": {path: "/custom/lootbert.png"},
    "milbert": {path: "/custom/milbert.png"},
    "mirbert": {path: "/custom/mirbert.png"},
    "moodbert": {path: "/custom/moodbert.png"},
    "nejbert": {path: "/custom/nejbert.png"},
    "neobert": {path: "/custom/neobert.png"},
    "odbert": {path: "/custom/odbert.png"},
    "pleurbert": {path: "/custom/pleurbert.png"},
    "pobert": {path: "/custom/pobert.png"},
    "raubert": {path: "/custom/raubert.png"},
    "rebert": {path: "/custom/rebert.png"},
    "redbert": {path: "/custom/redbert.png"},
    "sebert": {path: "/custom/sebert.png"},
    "shelbert": {path: "/custom/shelbert.png"},
    "squibert": {path: "/custom/squibert.png"},
    "STARKbert": {path: "/custom/STARKbert.png"},
    "sylbert": {path: "/custom/sylbert.png"},
    "tarbert": {path: "/custom/tarbert.png"},
    "tbert": {path: "/custom/tbert.png"},
    "tenbert": {path: "/custom/tenbert.png"},
    "udbert": {path: "/custom/udbert.png"},
    "wenbert": {path: "/custom/wenbert.png"}
}