export const sampleWorldBlobbers = [
    {
        id: 1,
        name: "Mr Nanami",
        blobber: 2,
        blob1: 1,
        blob2: 2,
        blob3: 3,
        blob4: 4,
        blob5: 5,
        blob6: 6,
        totalGames: 88,
        winRate: "88%",
    },

    {
        id: 2,
        name: "KingDominator",
        blobber: 3,
        blob1: 7,
        blob2: 8,
        blob3: 9,
        blob4: 10,
        blob5: 11,
        blob6: 12,
        totalGames: 69,
        winRate: "88%",
    },

    {
        id: 3,
        name: "Picasso",
        blobber: 4,
        blob1: 13,
        blob2: 14,
        blob3: 15,
        blob4: 16,
        blob5: 17,
        blob6: 18,
        totalGames: 88,
        winRate: "69%",
    },

    {
        id: 4,
        name: "CaveManBlobber",
        blobber: 5,
        blob1: 19,
        blob2: 20,
        blob3: 21,
        blob4: 22,
        blob5: 23,
        blob6: 24,
        totalGames: 69,
        winRate: "69%",
    },

    {
        id: 5,
        name: "SheepSheepGal",
        blobber: 6,
        blob1: 25,
        blob2: 26,
        blob3: 27,
        blob4: 28,
        blob5: 29,
        blob6: 30,
        totalGames: 33,
        winRate: "33%",
    },

    {
        id: 6,
        name: "BeeBeeBee",
        blobber: 7,
        blob1: 31,
        blob2: 32,
        blob3: 33,
        blob4: 34,
        blob5: 35,
        blob6: 36,
        totalGames: 33,
        winRate: "33%",
    },
]