[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x446f1f19ba951b59935df72974f8ba6060e5fbb411ca21d3e3e3812e3eb8df8"
transaction_hash = "0x7f1456c94b5cc20a043c7acb7e183a31b57b6de82699b062498189f8aae9d0b"
block_number = 3
seed = "dojo_starter"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x7ec42d76c6d876b8f219c20b6a152fe35fe2afc62c471b29ba689c2f6a075b3"
class_hash = "0x1d9defcdd0a85810e88f34def5030abb3f56c7f528db876092dd0a4adc879fd"
original_class_hash = "0x1d9defcdd0a85810e88f34def5030abb3f56c7f528db876092dd0a4adc879fd"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"

[[contracts]]
kind = "DojoContract"
address = "0x554eddebb282c17b8dce34c01ed146a67d96c39d8ca5c1d09d32188fb79d37c"
class_hash = "0x7971ed306d3cf1713df280d66f61dc04820d383262a40a621c3900b2cba47c5"
original_class_hash = "0x7971ed306d3cf1713df280d66f61dc04820d383262a40a621c3900b2cba47c5"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/dojo_starter_systems_lobby_lobby.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::lobby::lobby"

[[models]]
kind = "DojoModel"
class_hash = "0x3a7305310c7b2884ffc76c0337e9ca7062774d83895db48f5f698afedd74ea7"
original_class_hash = "0x3a7305310c7b2884ffc76c0337e9ca7062774d83895db48f5f698afedd74ea7"
abi = "abis/deployments/models/dojo_starter_models_blobert_blobert_1_blobert_one.json"
name = "dojo_starter::models::blobert::blobert_1::blobert_one"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "blobert_id"
type = "u8"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x263bba5fd559f8a5928728b0f7ed835e3832d9e64f39676cbf3fa6d675299c7"
original_class_hash = "0x263bba5fd559f8a5928728b0f7ed835e3832d9e64f39676cbf3fa6d675299c7"
abi = "abis/deployments/models/dojo_starter_models_blobert_blobert_2_blobert_two.json"
name = "dojo_starter::models::blobert::blobert_2::blobert_two"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "blobert_id"
type = "u8"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x56297efee701c2eaf6c857d50a45446251f982102cda82574dfa337733cde73"
original_class_hash = "0x56297efee701c2eaf6c857d50a45446251f982102cda82574dfa337733cde73"
abi = "abis/deployments/models/dojo_starter_models_blobert_blobert_3_blobert_three.json"
name = "dojo_starter::models::blobert::blobert_3::blobert_three"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "blobert_id"
type = "u8"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3fdc5f28a0a38ab0fab5a3eadbcddba474143209c518764aec4c9b7065a9ceb"
original_class_hash = "0x3fdc5f28a0a38ab0fab5a3eadbcddba474143209c518764aec4c9b7065a9ceb"
abi = "abis/deployments/models/dojo_starter_models_blobert_blobert_4_blobert_four.json"
name = "dojo_starter::models::blobert::blobert_4::blobert_four"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "blobert_id"
type = "u8"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x504f3a3a2c1a45bcb269b61023725dc989b9f889363b7add294d4a44cd66c79"
original_class_hash = "0x504f3a3a2c1a45bcb269b61023725dc989b9f889363b7add294d4a44cd66c79"
abi = "abis/deployments/models/dojo_starter_models_blobert_blobert_5_blobert_five.json"
name = "dojo_starter::models::blobert::blobert_5::blobert_five"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "blobert_id"
type = "u8"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x56a4ca3c9ba7f73968b3b6b9fd693a009a4fd8790ddaf4947acfac64037c269"
original_class_hash = "0x56a4ca3c9ba7f73968b3b6b9fd693a009a4fd8790ddaf4947acfac64037c269"
abi = "abis/deployments/models/dojo_starter_models_blobert_blobert_6_blobert_six.json"
name = "dojo_starter::models::blobert::blobert_6::blobert_six"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "blobert_id"
type = "u8"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x157b06c275a10cc44b46eadb570f785297bcf7b762d97ba078beed67d0a7eb"
original_class_hash = "0x157b06c275a10cc44b46eadb570f785297bcf7b762d97ba078beed67d0a7eb"
abi = "abis/deployments/models/dojo_starter_models_blobert_lineup_blobert_lineup.json"
name = "dojo_starter::models::blobert_lineup::blobert_lineup"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "blobert_1"
type = "u8"
key = false

[[models.members]]
name = "blobert_2"
type = "u8"
key = false

[[models.members]]
name = "blobert_3"
type = "u8"
key = false

[[models.members]]
name = "blobert_4"
type = "u8"
key = false

[[models.members]]
name = "blobert_5"
type = "u8"
key = false

[[models.members]]
name = "blobert_6"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2135f5e0e80de33420eb25b78364d4aa62fbbdc0cac9130673220ce922ec861"
original_class_hash = "0x2135f5e0e80de33420eb25b78364d4aa62fbbdc0cac9130673220ce922ec861"
abi = "abis/deployments/models/dojo_starter_models_blobert_pokedex_blobert_pokedex.json"
name = "dojo_starter::models::blobert_pokedex::blobert_pokedex"

[[models.members]]
name = "blobert_id"
type = "u128"
key = true

[[models.members]]
name = "blobert_name"
type = "felt252"
key = false

[[models.members]]
name = "health"
type = "u8"
key = false

[[models.members]]
name = "attack"
type = "u8"
key = false

[[models.members]]
name = "special_attack"
type = "u8"
key = false

[[models.members]]
name = "special_defense"
type = "u8"
key = false

[[models.members]]
name = "speed"
type = "u8"
key = false

[[models.members]]
name = "move_set"
type = "MoveSet"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7be4c19cce05f830a42bd9afd3c8ebb6e3e56785a5323fdcf5757b53ec68c61"
original_class_hash = "0x7be4c19cce05f830a42bd9afd3c8ebb6e3e56785a5323fdcf5757b53ec68c61"
abi = "abis/deployments/models/dojo_starter_models_move_book_move_book.json"
name = "dojo_starter::models::move_book::move_book"

[[models.members]]
name = "move_id"
type = "u128"
key = true

[[models.members]]
name = "move_name"
type = "felt252"
key = false

[[models.members]]
name = "damage"
type = "u8"
key = false

[[models.members]]
name = "move_type"
type = "MoveType"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6a77dd1dff1f69eef7f8ce91bb5951420c73dc7ac175221dccf2485210fab60"
original_class_hash = "0x6a77dd1dff1f69eef7f8ce91bb5951420c73dc7ac175221dccf2485210fab60"
abi = "abis/deployments/models/dojo_starter_models_move_set_move_set.json"
name = "dojo_starter::models::move_set::move_set"

[[models.members]]
name = "blobert_id"
type = "u128"
key = true

[[models.members]]
name = "move_1"
type = "u128"
key = false

[[models.members]]
name = "move_2"
type = "u128"
key = false

[[models.members]]
name = "move_3"
type = "u128"
key = false

[[models.members]]
name = "move_4"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x23c28dcfad6be01ca6509fdb35fd2bed6622238397613c60da5d387a43c38d0"
original_class_hash = "0x23c28dcfad6be01ca6509fdb35fd2bed6622238397613c60da5d387a43c38d0"
abi = "abis/deployments/models/dojo_starter_models_moves_moves.json"
name = "dojo_starter::models::moves::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5180bf97a23cbc84cdf22e94b328f12c937515db9df9ee961536dd7acc73d3e"
original_class_hash = "0x5180bf97a23cbc84cdf22e94b328f12c937515db9df9ee961536dd7acc73d3e"
abi = "abis/deployments/models/dojo_starter_models_player_player.json"
name = "dojo_starter::models::player::player"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "total_duels"
type = "u16"
key = false

[[models.members]]
name = "total_wins"
type = "u16"
key = false

[[models.members]]
name = "total_losses"
type = "u16"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2e9c42b868b520d54bff1b7f4c9b91f39bb2e2ad1c39d6484fb5d8a95382e01"
original_class_hash = "0x2e9c42b868b520d54bff1b7f4c9b91f39bb2e2ad1c39d6484fb5d8a95382e01"
abi = "abis/deployments/models/dojo_starter_models_position_position.json"
name = "dojo_starter::models::position::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
